spring.application.name=FurniQ

spring.datasource.url=jdbc:postgresql://localhost:5432/Furniq
spring.datasource.username=nethmina
spring.datasource.password=12345

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

jwt.secret=fa8c24156bb4118970721bcc52a76c69c995b75c44c55b28fa96ba31f62635b051f4f76fa3faec9f03fb66a738131af9


# Spring Mail Configuration (for Gmail)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=maheeshanethmina@gmail.com
spring.mail.password=yeqb elhs priw jgsh


# Enable STARTTLS and Auth
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.servlet.multipart.max-file-size=5MB 
spring.servlet.multipart.max-request-size=6MB